[package]
name = "ses-analysis"
description = "Code-agnostic provision pipeline for SES"
publish = false
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
ses-engineer = { workspace = true }
ses-adapter = { workspace = true }
thiserror = { workspace = true }
