[package]
name = "ses-provision"
description = "Provision DSL parser and compiler for SES"
publish = false
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
ses-engineer = { workspace = true }
ses-analysis = { workspace = true }
thiserror = { workspace = true }
