[package]
name = "ses-engineer"
description = "Engineering quantities, units, and expression types for SES"
publish = false
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
adele-ring = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
